[workspace]
allow_dirty = true
# dependencies_update = false # run `cargo update`
git_release_enable = false

[[package]]
name = "structable"
git_release_enable = true
changelog_include = ["structable_derive"]
version_group = "structable"

[[package]]
name = "structable_derive"
git_release_enable = true
version_group = "structable"
